version: '3.6'

services:
  keycloak:
    restart: unless-stopped
    image: quay.io/keycloak/keycloak:18.0
    command: start-dev #see https://www.keycloak.org/server/configuration-production
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: postgresql
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_SCHEMA: public
      DB_PASSWORD: superDuperSecret
      KEYCLOAK_LOGLEVEL: INFO
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "28080:8080"
    depends_on:
      - postgresql
  postgresql:
    image: postgres:14
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: verySecurePasswordForDevelopment
    ports:
      - "25432:5432"
    volumes:
      - postgresql_data:/var/lib/postgresql/data
      - ./config/postgresql/initdb:/docker-entrypoint-initdb.d

  shift-planner-api:
    restart: unless-stopped
    image: ghcr.io/muddi-markt/shiftplanner/api:v1
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__DefaultConnection: "Host=postgresql;Database=shiftplanner;Username=postgres;Password=verySecurePasswordForDevelopment"
      Keycloak__Authority: "http://keycloak:8080/auth/realms/shiftplanner"
      Keycloak__ClientId: "shiftplanner-api"
      Keycloak__ClientSecret: "superDuperSecret"
    ports:
      - "8008:80"
    depends_on:
      - keycloak
      - postgresql
    network_mode: "host"

  shift-planner-client:
    restart: unless-stopped
    image: ghcr.io/muddi-markt/shiftplanner/client:v1
    ports:
      - "8009:80"
    volumes:
      - ./config/customization:/usr/share/nginx/html/customization
      - ./config/manifest.json:/usr/share/nginx/html/manifest.json
    network_mode: "host"

volumes:
  postgresql_data: