version: '3.6'

services:
  keycloak:
    restart: unless-stopped
    image: quay.io/keycloak/keycloak:15.0.2
    command: -Dkeycloak.profile.feature.upload_scripts=enabled
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: postgresql
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_SCHEMA: public
      DB_PASSWORD: verySecurePasswordForDevelopment
      KEYCLOAK_LOGLEVEL: INFO
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
    ports:
      - "28080:8080"
    depends_on:
      - postgresql
  postgresql:
    image: postgres:13
    restart: unless-stopped
    environment:
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: verySecurePasswordForDevelopment
      POSTGRES_DB: keycloak
    ports:
      - "25432:5432"
    volumes:
      - postgresql_data:/var/lib/postgresql/data
volumes:
  postgresql_data: