name: Publish Docker image

on:
  push:
    branches:
      - main
env:
  REGISTRY: ghcr.io

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    strategy:
      matrix:
        app: [
          { path: "Muddi.ShiftPlanner.Client", name: "client" },
          { path: "Muddi.ShiftPlanner.Server.Api", name: "api" },
          { path: "Muddi.ShiftPlanner.Services.Alerting", name: "alerting" },
        ]
    steps:
      - uses: actions/checkout@v4

      - name: Convert repository name to lowercase
        id: repo_lower
        run: echo "lower_repo=$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      - name: Log in to the Container registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Set up Docker Build
        uses: docker/setup-buildx-action@v1

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./${{ matrix.app.path }}/Dockerfile
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.lower_repo }}/${{ matrix.app.name }}:${{ github.sha }}