name: Publish Docker image

on:
  push:
    branches:
      - main
      - develop
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    strategy:
      matrix:
        app: [
          {path: "Muddi.ShiftPlanner.Client", name: "client"},
          {path: "Muddi.ShiftPlanner.Server.Api", name: "api"},
          {path: "Muddi.ShiftPlanner.Services.Alerting", name: "alerting"},
        ]
    steps:
      - uses: actions/checkout@v4
      - name: Log in to the Container registry
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Build
        uses: docker/setup-buildx-action@v1

      - name: Log in to the GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./${{ matrix.app.path }}/Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository }}/${{ matrix.app.name }}:${{ github.sha }}
          build-args: |
            NETWORK=host
          # Verwende load anstatt push, um mit buildx zu bauen und dann manuell zu pushen
          load: true
      - name: Create and push image with network host
        run: |
          docker buildx build --tag ghcr.io/${{ github.repository }}/${{ matrix.app.name }}:${{ github.sha }} --network host --push .